module.exports = () => {
    const data = {
        recipes: [
            {
                id: 1,
                imageUrl: "/images/food/dog/dog1.png",
                imageAlt: "Veggie Meat",
                runTime: "40 min",
                title: "Veggie Meat",
                rating: 2,
                reviewCount: 12,
                type: "dog",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 2,
                imageUrl: "/images/food/dog/dog2.png",
                imageAlt: "Whey Protein",
                runTime: "60 min",
                title: "Whey Protein",
                rating: 4,
                reviewCount: 22,
                type: "dog",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 3,
                imageUrl: "/images/food/cat/cat1.png",
                imageAlt: "japanese food for cats",
                runTime: "40 min",
                title: "Catpanese",
                rating: 5,
                reviewCount: 19,
                type: "cat",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 4,
                imageUrl: "/images/food/cat/cat2.png",
                imageAlt: "Cat Fit lowcarb poke",
                runTime: "30 min",
                title: "Cat Fit",
                rating: 1,
                reviewCount: 17,
                type: "cat",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 5,
                imageUrl: "/images/food/fish/fish1.png",
                imageAlt: "100% organic seaweed salad",
                runTime: "20 min",
                title: "Seaweed Salad",
                rating: 5,
                reviewCount: 59,
                type: "fish",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 6,
                imageUrl: "/images/food/bird/bird1.png",
                imageAlt: "Enpowered Corn for sharpening growth",
                runTime: "55 min",
                title: "Enpowered Corn",
                rating: 3,
                reviewCount: 41,
                type: "bird",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 7,
                imageUrl: "/images/food/reptile/reptile1.png",
                imageAlt: "High protein Insect gourmet",
                runTime: "25 min",
                title: "Insect Gourmet",
                rating: 4,
                reviewCount: 35,
                type: "reptile",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 8,
                imageUrl: "/images/food/reptile/reptile2.png",
                imageAlt: "Rat fried fringers on coconut oil",
                runTime: "35 min",
                title: "Rat Fingers",
                rating: 3,
                reviewCount: 23,
                type: "reptile",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
            {
                id: 9,
                imageUrl: "/images/food/rodent/rodent1.png",
                imageAlt: "Gluten free hamster portion",
                runTime: "50 min",
                title: "Hamster Portion",
                rating: 4,
                reviewCount: 14,
                type: "rodent",
                recipe: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            },
        ],
    }

    return data;

}